import { describe, expect, it } from "vitest";
import fixture from "./fixtures/site-topology.json";
import {
    CLIENT_CONNECTIONS,
    ISSUE_SEVERITIES,
    IncompatibleSchemaError,
    LINK_MEDIA,
    NODE_KINDS,
    NODE_STATES,
    SCHEMA_VERSION,
    TOPOLOGY_STATUSES,
    UNRESOLVED_REASONS,
    parseSnapshot,
    type SiteTopology,
    type TopologyEdge,
    type TopologyIssue,
    type TopologyNode,
    type TopologyTruncation,
    type TopologyUnresolved,
} from "../src/contract";

type FieldSpec =
    | { kind: "string" | "number"; optional?: true }
    | { kind: "enum"; values: readonly string[]; optional?: true };

// `satisfies Record<keyof X, FieldSpec>` makes TypeScript reject a spec that
// misses or invents a field, so these specs cannot drift from contract.ts.
const NODE_SPEC = {
    id: { kind: "string" },
    kind: { kind: "enum", values: NODE_KINDS },
    name: { kind: "string" },
    state: { kind: "enum", values: NODE_STATES },
    model: { kind: "string", optional: true },
    ha_device_id: { kind: "string", optional: true },
    connection: { kind: "enum", values: CLIENT_CONNECTIONS, optional: true },
    vlan_id: { kind: "number", optional: true },
    network_name: { kind: "string", optional: true },
} satisfies Record<keyof TopologyNode, FieldSpec>;

const EDGE_SPEC = {
    source: { kind: "string" },
    target: { kind: "string" },
    medium: { kind: "enum", values: LINK_MEDIA },
    speed_mbps: { kind: "number", optional: true },
    parent_port: { kind: "number", optional: true },
    child_port: { kind: "number", optional: true },
    poe_power_w: { kind: "number", optional: true },
} satisfies Record<keyof TopologyEdge, FieldSpec>;

const ISSUE_SPEC = {
    code: { kind: "string" },
    severity: { kind: "enum", values: ISSUE_SEVERITIES },
} satisfies Record<keyof TopologyIssue, FieldSpec>;

const UNRESOLVED_SPEC = {
    node_id: { kind: "string" },
    reason: { kind: "enum", values: UNRESOLVED_REASONS },
} satisfies Record<keyof TopologyUnresolved, FieldSpec>;

const TRUNCATION_SPEC = {
    clients_total: { kind: "number" },
    clients_included: { kind: "number" },
} satisfies Record<keyof TopologyTruncation, FieldSpec>;

const LIST_FIELDS = [
    "nodes",
    "edges",
    "issues",
    "unresolved",
    "truncation",
] as const;
const SNAPSHOT_SPEC = {
    schema_version: { kind: "number" },
    entry_id: { kind: "string" },
    site_id: { kind: "string" },
    site_name: { kind: "string" },
    revision: { kind: "string" },
    status: { kind: "enum", values: TOPOLOGY_STATUSES },
} satisfies Record<
    Exclude<keyof SiteTopology, (typeof LIST_FIELDS)[number]>,
    FieldSpec
>;

function checkObject(
    value: unknown,
    spec: Record<string, FieldSpec>,
    where: string,
    extra: readonly string[] = [],
): void {
    expect(typeof value, where).toBe("object");
    const record = value as Record<string, unknown>;
    for (const key of Object.keys(record)) {
        expect(
            [...Object.keys(spec), ...extra],
            `${where}: unexpected field "${key}"`,
        ).toContain(key);
    }
    for (const [key, field] of Object.entries(spec)) {
        const v = record[key];
        if (v === undefined) {
            expect(field.optional, `${where}: missing "${key}"`).toBe(true);
        } else if (field.kind === "enum") {
            expect(field.values, `${where}.${key}`).toContain(v);
        } else {
            expect(typeof v, `${where}.${key}`).toBe(field.kind);
        }
    }
}

function checkSnapshot(raw: unknown): void {
    checkObject(raw, SNAPSHOT_SPEC, "snapshot", LIST_FIELDS);
    const s = raw as SiteTopology;
    s.nodes.forEach((n, i) => checkObject(n, NODE_SPEC, `nodes[${i}]`));
    s.edges.forEach((e, i) => checkObject(e, EDGE_SPEC, `edges[${i}]`));
    s.issues.forEach((x, i) => checkObject(x, ISSUE_SPEC, `issues[${i}]`));
    s.unresolved.forEach((u, i) =>
        checkObject(u, UNRESOLVED_SPEC, `unresolved[${i}]`),
    );
    if (s.truncation !== null)
        checkObject(s.truncation, TRUNCATION_SPEC, "truncation");
}

describe("shared contract fixture (generated by tests/test_topology.py)", () => {
    it("matches contract.ts field for field", () => {
        checkSnapshot(fixture);
    });

    it("parses unchanged and references only known nodes", () => {
        const snapshot = parseSnapshot(fixture);
        expect(snapshot.schema_version).toBe(SCHEMA_VERSION);
        const ids = new Set(snapshot.nodes.map((n) => n.id));
        for (const edge of snapshot.edges) {
            expect(ids.has(edge.source) && ids.has(edge.target)).toBe(true);
        }
        // source is the CHILD: the core switch hangs off the gateway.
        expect(snapshot.edges).toContainEqual(
            expect.objectContaining({
                source: "dev:uuid-core",
                target: "dev:uuid-gw",
            }),
        );
    });

    it("rejects a field the contract does not define", () => {
        const tampered = JSON.parse(JSON.stringify(fixture)) as {
            nodes: Record<string, unknown>[];
        };
        tampered.nodes[0]!.mac = "aa:bb:cc:dd:ee:ff";
        expect(() => checkSnapshot(tampered)).toThrow(/unexpected field "mac"/);
    });
});

describe("parseSnapshot", () => {
    it("rejects another schema version as incompatible", () => {
        expect(() => parseSnapshot({ ...fixture, schema_version: 2 })).toThrow(
            IncompatibleSchemaError,
        );
    });

    it.each([
        null,
        [],
        "x",
        { ...fixture, nodes: "no" },
        { ...fixture, revision: 5 },
    ])("rejects a malformed payload %#", (raw) => {
        expect(() => parseSnapshot(raw)).toThrow(TypeError);
    });
});
