---
name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Run tests & coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ffmpeg \
            libturbojpeg

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14.2

      - name: Install dependencies
        run: |
          uv venv --python 3.14.2
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          uv pip install . ".[dev]" homeassistant

      - name: Run tests and generate coverage report
        run: |
          pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          files: ./coverage.xml
